// <auto-generated />
using System;
using LastWork.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LastWork.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190218194006_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LastWork.Models.Instructions.Instruction", b =>
                {
                    b.Property<long>("InstructionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("InstructionName");

                    b.HasKey("InstructionId");

                    b.ToTable("instructions");
                });

            modelBuilder.Entity("LastWork.Models.Instructions.InstructionStep", b =>
                {
                    b.Property<long>("InstructionStepId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("InstructionId");

                    b.Property<string>("StepDescription");

                    b.Property<string>("StepName");

                    b.HasKey("InstructionStepId");

                    b.HasIndex("InstructionId");

                    b.ToTable("steps");
                });

            modelBuilder.Entity("LastWork.Models.Instructions.InstructionStep", b =>
                {
                    b.HasOne("LastWork.Models.Instructions.Instruction")
                        .WithMany("Steps")
                        .HasForeignKey("InstructionId");
                });
#pragma warning restore 612, 618
        }
    }
}
